//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Churn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change
    {
        public int Id { get; set; }
        public  Microsoft.TeamFoundation.VersionControl.Client.ChangeType ChangeType { get; set; }
    
        public virtual Changeset Changeset { get; set; }
        public virtual ItemVersion ItemVersion { get; set; }
        public virtual DiffStat DiffStats { get; set; }
    }
}
