//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Churn
{
    using System;
    
    public enum ChangesetStatus : int
    {
        New = 0,
        InProgress = 1,
        Done = 2,
        Error = 3
    }
}
