//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Churn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChurnContainer : DbContext
    {
        public ChurnContainer()
            : base("name=ChurnContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Project> Projects { get; set; }
        public DbSet<Changeset> Changesets { get; set; }
        public DbSet<Change> Changes { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<ItemVersion> ItemVersions { get; set; }
        public DbSet<DiffStat> DiffStats { get; set; }
    }
}
