//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Churn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiffStat
    {
        public int Id { get; set; }
        public long InitialLineCount { get; set; }
        public long Added { get; set; }
        public long Modified { get; set; }
        public long Deleted { get; set; }
        public long FinalLineCount { get; set; }
    
        public virtual Change Change { get; set; }
    }
}
