//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Churn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Versions = new HashSet<ItemVersion>();
        }
    
        public int Id { get; set; }
        public string ServerItem { get; set; }
        public Microsoft.TeamFoundation.VersionControl.Client.ItemType ItemType { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<ItemVersion> Versions { get; set; }
    }
}
